from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import TemplateView

import candidates.views as views

from .feeds import RecentChangesFeed

urlpatterns = patterns('',
    url(r'^$', views.ConstituencyPostcodeFinderView.as_view(), name='finder'),
    url(r'^lookup/name$', views.ConstituencyNameFinderView.as_view(), name='lookup-name'),
    url(r'^lookup/postcode$', views.ConstituencyPostcodeFinderView.as_view(), name='lookup-postcode'),
    url(r'^constituencies$', views.ConstituencyListView.as_view(), name='constituencies'),
    url(r'^constituency/(?P<mapit_area_id>\d+)/(?P<ignored_slug>.*).csv$',
        views.ConstituencyDetailCSVView.as_view(),
        name='constituency_csv'),
    url(r'^constituency/(?P<mapit_area_id>\d+)/(?P<ignored_slug>.*)$',
        views.ConstituencyDetailView.as_view(),
        name='constituency'),
    url(r'^constituency/lock$',
        views.ConstituencyLockView.as_view(),
        name='constituency-lock'),
    url(r'^candidacy$',
        views.CandidacyView.as_view(),
        name='candidacy-create'),
    url(r'^candidacy/delete$',
        views.CandidacyDeleteView.as_view(),
        name='candidacy-delete'),
    url(r'^person/create/$',
        views.NewPersonView.as_view(),
        name='person-create'),
    url(r'^person/(?P<person_id>\d+)/update$',
        views.UpdatePersonView.as_view(),
        name='person-update'),
    url(r'^person/(?P<person_id>\d+)/revert$',
        views.RevertPersonView.as_view(),
        name='person-revert'),
    url(r'^person/(?P<person_id>\d+)/merge$',
        views.MergePeopleView.as_view(),
        name='person-merge'),
    url(r'^person/(?P<person_id>\d+)(?:/(?P<ignored_slug>.*))?$',
        views.PersonView.as_view(),
        name='person-view'),
    url(r'^party/(?P<organization_id>[a-z-]+:\d+)/(?P<ignored_slug>.*)$',
        views.PartyDetailView.as_view(),
        name='party'),
    url(r'^parties/?$',
        views.PartyListView.as_view(),
        name='party-list'),
    url(r'^recent-changes$',
        views.RecentChangesView.as_view(),
        name='recent-changes'),
    url(r'^leaderboard$',
        views.LeaderboardView.as_view(),
        name='leaderboard'),
    url(r'^leaderboard/contributions.csv',
        views.UserContributions.as_view(),
        name='user-contributions'),
    url(r'^numbers/', include('cached_counts.urls')),
    url(r'^moderation/', include('moderation_queue.urls')),
    url(r'^feeds/changes.xml', RecentChangesFeed(), name='changes_feed'),
    url(r'^help/api', views.HelpApiView.as_view(), name='help-api'),
    url(r'^help/about', views.HelpAboutView.as_view(), name='help-about'),
    url(r'^help/privacy',
        TemplateView.as_view(template_name="candidates/privacy.html"),
        name='help-privacy'),
    url(r'^copyright-question',
        views.AskForCopyrightAssigment.as_view(),
        name='ask-for-copyright-assignment'),
    url(r'^person/invalidate$',
        views.InvalidatePersonView.as_view(),
        name='person-cache-invalidate'),
    url(r'^constituency/invalidate$',
        views.InvalidatePostView.as_view(),
        name='constituency-cache-invalidate'),
    url(r'^admin/', include(admin.site.urls)),
)
