#!/bin/sh

set -e

echo "Creating parties..."
./manage.py candidates_update_parties \
    https://raw.githubusercontent.com/mhl/UK-Political-Parties/gh-pages/data/parties.csv
echo "Creating everything else..."
./manage.py candidates_create_popit
