#!/bin/sh

set -e

echo "Creating parties in PopIt from EC data..."
./manage.py candidates_update_popit_parties_from_ec_data

echo "Creating everything else..."
./manage.py candidates_create_popit

echo "Dumping PopIt parties to JSON..."
./manage.py candidates_dump_popit_parties_to_json \
    data/all-parties-from-popit.json
