# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _


class CantonSelectorForm(forms.Form):

    # This could be a ModelChoiceField, except that we want to have
    # the two alternative names for Aguirre / Quepos with the same
    # value.
    canton_area_id = forms.ChoiceField(
        label=_('Select your canton'),
        choices=[
            ('none', ''),
            ('106', u'Abangares'),
            ('144', u'Acosta'),
            ('133', u'Aguirre'),
            ('83', u'Alajuela'),
            ('145', u'Alajuelita'),
            ('84', u'Alfaro Ruiz'),
            ('98', u'Alvarado'),
            ('146', u'Aserrí'),
            ('85', u'Atenas'),
            ('107', u'Bagaces'),
            ('117', u'Barva'),
            ('118', u'Belén'),
            ('134', u'Buenos Aires'),
            ('108', u'Cañas'),
            ('109', u'Carrillo'),
            ('99', u'Cartago'),
            ('135', u'Corredores'),
            ('136', u'Coto Brus'),
            ('147', u'Curridabat'),
            ('148', u'Desamparados'),
            ('149', u'Dota'),
            ('100', u'El Guarco'),
            ('150', u'Escazú'),
            ('137', u'Esparza'),
            ('119', u'Flores'),
            ('138', u'Garabito'),
            ('151', u'Goicoechea'),
            ('139', u'Golfito'),
            ('86', u'Grecia'),
            ('127', u'Guácimo'),
            ('87', u'Guatuso'),
            ('120', u'Heredia'),
            ('110', u'Hojancha'),
            ('101', u'Jiménez'),
            ('111', u'La Cruz'),
            ('102', u'La Unión'),
            ('152', u'León Cortés'),
            ('112', u'Liberia'),
            ('128', u'Limón'),
            ('88', u'Los Chiles'),
            ('129', u'Matina'),
            ('153', u'Montes de Oca'),
            ('140', u'Montes de Oro'),
            ('154', u'Mora'),
            ('155', u'Moravia'),
            ('113', u'Nandayure'),
            ('89', u'Naranjo'),
            ('114', u'Nicoya'),
            ('103', u'Oreamuno'),
            ('90', u'Orotina'),
            ('141', u'Osa'),
            ('91', u'Palmares'),
            ('104', u'Paraíso'),
            ('142', u'Parrita'),
            ('156', u'Pérez Zeledón'),
            ('92', u'Poás'),
            ('130', u'Pococí'),
            ('143', u'Puntarenas'),
            ('157', u'Puriscal'),
            ('133', u'Quepos'),
            ('93', u'San Carlos'),
            ('121', u'San Isidro'),
            ('158', u'San José'),
            ('94', u'San Mateo'),
            ('122', u'San Pablo'),
            ('123', u'San Rafael'),
            ('95', u'San Ramón'),
            ('159', u'Santa Ana'),
            ('124', u'Santa Bárbara'),
            ('115', u'Santa Cruz'),
            ('125', u'Santo Domingo'),
            ('126', u'Sarapiquí'),
            ('131', u'Siquirres'),
            ('132', u'Talamanca'),
            ('160', u'Tarrazú'),
            ('161', u'Tibás'),
            ('116', u'Tilarán'),
            ('105', u'Turrialba'),
            ('162', u'Turrubares'),
            ('96', u'Upala'),
            ('97', u'Valverde Vega'),
            ('163', u'Vásquez de Coronado'),
            ('84', u'Zarcero'),
        ]
    )
