from collections import defaultdict
from optparse import make_option
from os import chmod, rename
from os.path import dirname
from tempfile import NamedTemporaryFile

from django.core.management.base import BaseCommand, CommandError
from django.db.models import F

from candidates.csv_helpers import list_to_csv
from candidates.models import PersonExtra
from elections.models import Election


class Command(BaseCommand):

    help = "Output CSV files for all elections"
    args = "<BASE-OUTPUT-FILENAME>"

    option_list = BaseCommand.option_list + (
        make_option('-o', '--output',
                    dest='output_filename',
                    help='The filename to write CSV to'),
        make_option('-e', '--election',
                    dest='election',
                    help='The election identifier',
                    default='2015'),
    )

    def handle(self, *args, **options):
        if len(args) != 1:
            msg = "You must supply the prefix for output filenames"
            raise CommandError(msg)
        output_prefix = args[0]

        all_elections = list(Election.objects.all())
        people_by_election = defaultdict(list)

        # Get the candidates for a particular election:
        for election in all_elections:
            for person_extra in PersonExtra.objects.filter(
                    base__memberships__extra__election=election,
                    base__memberships__role=election.candidate_membership_role
            ).select_related('base'):
                people_by_election[election.slug].append(
                    person_extra.as_dict(election)
                )
        # And then get the candidates for all elections, where we show
        # information about the most recent election.  Unfortunately
        # this may not be well defined, since it's conceivable that
        # someone is standing in two different current elections
        # taking place on the same date.  This file is only generated
        # so that the same files are generated by YourNextMP - we
        # probably shouldn't generate it in the future.
        for person_extra in PersonExtra.objects.all():
            elections = list(Election.objects.filter(
                candidacies__base__person=person_extra.base.id,
                candidacies__base__role=F('candidate_membership_role')
            ).order_by('current', 'election_date'))
            if not elections:
                continue
            election = elections[-1]
            people_by_election[None].append(
                person_extra.as_dict(election)
            )
        for election in all_elections + [None]:
            if election is None:
                output_filename = output_prefix + '-all.csv'
                election_slug = None
            else:
                output_filename = output_prefix + '-' + election.slug + '.csv'
                election_slug = election.slug
            people_data = people_by_election[election_slug]
            csv = list_to_csv(people_data)
            # Write to a temporary file and atomically rename into place:
            ntf = NamedTemporaryFile(
                delete=False,
                dir=dirname(output_filename)
            )
            ntf.write(csv)
            chmod(ntf.name, 0o644)
            rename(ntf.name, output_filename)
